import { useMemo } from 'react';

// Builds the six memoized domain-context values (see src/context/ and
// AGENTS.md's Context Architecture section) from the raw state/handlers
// App.jsx assembles from its various hooks. Kept separate from App.jsx so
// the composition root isn't also the place doing this bookkeeping —
// App.jsx just calls hooks and hands the results here.
export default function useAppProviderValues({
  // settings
  changeTheme,
  displayMode,
  handleDisplayModeChange,
  isCrtEnabled,
  isGlitching,
  isGodMode,
  isMatrixMode,
  setDisplayMode,
  setIsCrtEnabled,
  setIsMatrixMode,
  setSoundEnabled,
  soundEnabled,
  theme,
  // browser
  activeCategories,
  activeFilters,
  activeFiltersSet,
  counts,
  currentPage,
  draggedFavoriteId,
  dragOverFavoriteId,
  favoriteCount,
  favorites,
  filteredProjects,
  focusedCardIndex,
  handleCopyLink,
  handleDragEnd,
  handleDragOver,
  handleDragStart,
  handleDrop,
  handlePageChange,
  handleTagClick,
  hoveredTag,
  isMobileFiltersOpen,
  paginatedProjects,
  projectsMatchingQuery,
  randomSeed,
  searchInputRef,
  searchQuery,
  setActiveFilters,
  setCurrentPage,
  setFocusedCardIndex,
  setHoveredTag,
  setIsMobileFiltersOpen,
  setRandomSeed,
  setSearchQuery,
  setSortOption,
  sortOption,
  suggestedTags,
  toggleFavorite,
  toggleFilter,
  totalPages,
  totalProjects,
  // terminal
  handleTerminalKeyDown,
  handleTerminalSubmit,
  isHoloTerminalOpen,
  isTerminalClosing,
  isTerminalOpen,
  setIsHoloTerminalOpen,
  setIsTerminalClosing,
  setIsTerminalOpen,
  setTerminalInput,
  terminalEndRef,
  terminalHistory,
  terminalInput,
  terminalInputRef,
  // overlay
  addToast,
  clickEffects,
  closeContextMenu,
  closeProjectModal,
  contextMenu,
  handleContextMenu,
  handleProjectSelect,
  isDataMode,
  isIdle,
  isLockdown,
  isOmniOpen,
  isWarping,
  modalImageLoaded,
  modalRef,
  removeToast,
  selectedProject,
  setIsDataMode,
  setIsLockdown,
  setIsOmniOpen,
  setModalImageLoaded,
  setSelectedProject,
  toasts,
  // effects
  baseGridRef,
  canvasRef,
  deepGridRef,
  gridSpotlightRef,
  starfieldRef,
  // activity
  addActivityLog,
  bootLogs,
  bootStep,
  isBooting,
  scanProgress,
  showBootScreen,
  startScan,
  stopScan,
  userActivityLogs
}) {
  const settingsValue = useMemo(() => ({
    changeTheme,
    displayMode,
    handleDisplayModeChange,
    isCrtEnabled,
    isGlitching,
    isGodMode,
    isMatrixMode,
    isSoundEnabled: soundEnabled,
    setDisplayMode,
    setIsCrtEnabled,
    setIsMatrixMode,
    setIsSoundEnabled: setSoundEnabled,
    theme
  }), [changeTheme, displayMode, handleDisplayModeChange, isCrtEnabled, isGlitching, isGodMode, isMatrixMode, setDisplayMode, setIsCrtEnabled, setIsMatrixMode, setSoundEnabled, soundEnabled, theme]);

  const browserValue = useMemo(() => ({
    activeCategories,
    activeFilters,
    activeFiltersSet,
    counts,
    currentPage,
    draggedFavoriteId,
    dragOverFavoriteId,
    favoriteCount,
    favorites,
    filteredProjects,
    focusedCardIndex,
    handleCopyLink,
    handleDragEnd,
    handleDragOver,
    handleDragStart,
    handleDrop,
    handlePageChange,
    handleTagClick,
    hoveredTag,
    isMobileFiltersOpen,
    paginatedProjects,
    projectsMatchingQuery,
    randomSeed,
    searchInputRef,
    searchQuery,
    setActiveFilters,
    setCurrentPage,
    setFocusedCardIndex,
    setHoveredTag,
    setIsMobileFiltersOpen,
    setRandomSeed,
    setSearchQuery,
    setSortOption,
    sortOption,
    suggestedTags,
    toggleFavorite,
    toggleFilter,
    totalPages,
    totalProjects
  }), [activeCategories, activeFilters, activeFiltersSet, counts, currentPage, draggedFavoriteId, dragOverFavoriteId, favoriteCount, favorites, filteredProjects, focusedCardIndex, handleCopyLink, handleDragEnd, handleDragOver, handleDragStart, handleDrop, handlePageChange, handleTagClick, hoveredTag, isMobileFiltersOpen, paginatedProjects, projectsMatchingQuery, randomSeed, searchInputRef, searchQuery, setActiveFilters, setCurrentPage, setFocusedCardIndex, setHoveredTag, setIsMobileFiltersOpen, setRandomSeed, setSearchQuery, setSortOption, suggestedTags, toggleFavorite, toggleFilter, totalPages, totalProjects, sortOption]);

  const terminalValue = useMemo(() => ({
    handleTerminalKeyDown,
    handleTerminalSubmit,
    isHoloTerminalOpen,
    isTerminalClosing,
    isTerminalOpen,
    setIsHoloTerminalOpen,
    setIsTerminalClosing,
    setIsTerminalOpen,
    setTerminalInput,
    terminalEndRef,
    terminalHistory,
    terminalInput,
    terminalInputRef
  }), [handleTerminalKeyDown, handleTerminalSubmit, isHoloTerminalOpen, isTerminalClosing, isTerminalOpen, setIsHoloTerminalOpen, setIsTerminalClosing, setIsTerminalOpen, setTerminalInput, terminalEndRef, terminalHistory, terminalInput, terminalInputRef]);

  const overlayValue = useMemo(() => ({
    addToast,
    clickEffects,
    closeContextMenu,
    closeProjectModal,
    contextMenu,
    handleContextMenu,
    handleProjectSelect,
    isDataMode,
    isIdle,
    isLockdown,
    isOmniOpen,
    isWarping,
    modalImageLoaded,
    modalRef,
    removeToast,
    selectedProject,
    setIsDataMode,
    setIsLockdown,
    setIsOmniOpen,
    setModalImageLoaded,
    setSelectedProject,
    toasts
  }), [addToast, clickEffects, closeContextMenu, closeProjectModal, contextMenu, handleContextMenu, handleProjectSelect, isDataMode, isIdle, isLockdown, isOmniOpen, isWarping, modalImageLoaded, modalRef, removeToast, selectedProject, setIsDataMode, setIsLockdown, setIsOmniOpen, setModalImageLoaded, setSelectedProject, toasts]);

  const effectsValue = useMemo(() => ({
    baseGridRef,
    canvasRef,
    deepGridRef,
    gridSpotlightRef,
    starfieldRef
  }), [baseGridRef, canvasRef, deepGridRef, gridSpotlightRef, starfieldRef]);

  const activityValue = useMemo(() => ({
    addActivityLog,
    bootLogs,
    bootStep,
    isBooting,
    scanProgress,
    showBootScreen,
    startScan,
    stopScan,
    userActivityLogs
  }), [addActivityLog, bootLogs, bootStep, isBooting, scanProgress, showBootScreen, startScan, stopScan, userActivityLogs]);

  return { settingsValue, browserValue, terminalValue, overlayValue, effectsValue, activityValue };
}
